### ISSUE TITLE
Improve Debian package updates

### ISSUE THREAD

**Issue by lms-jk** [Hetsh/BashCommons#1]
Scraping packages.debian.org is unreliable and slow. Debian QA offers a [madison webpage](https://qa.debian.org/madison.php) where the latest version can be queried and there is a simple REST API on the backend that we can use. [rMadison](https://manpages.debian.org/buster/devscripts/rmadison.1.de.html) from the devscripts should be a good template.

**Comment by Hetsh** [comment]
Merged PR #2
